# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'habbits' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # Pods for habbits
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'RCTImage', # !!!!!
    ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'habbitsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end