# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'habbits' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for habbits
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'

  # Required by RNFirebase

  target 'habbitsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'habbits-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for habbits-tvOS

  target 'habbits-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
