import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'space-between',
    backgroundColor: '#3B495B',
  },
  headline: {
    paddingTop: 60,
    paddingLeft: 24,
    width: 308,
    fontFamily: 'Futura',
    fontSize: 35,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  wrapper: {
    marginTop: 20,
    alignItems: 'center',
    marginLeft: 24,
    marginRight: 24,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  item: {
    flex: 1,
  },
  habbitWrapper: {
    height: 105,
    width: 157,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  right: {
    alignSelf: 'flex-end',
  },
  left: {
    alignSelf: 'flex-start',
  },
  habbitTextBar: {
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    width: 157,
    height: 40.5,
    backgroundColor: '#576371',
  },
  habbitText: {
    width: 157,
    fontFamily: 'Futura',
    fontSize: 15,
    fontWeight: 'bold',
    color: '#dce0e6',
    textAlign: 'center',
  },
  sleepHabbitImage: {
    position: 'absolute',
    bottom: 0,
    marginLeft: 26.5,
    width: 104.5,
    height: 72,
  },
  journalHabbitImage: {
    position: 'absolute',
    top: '30%',
    width: 50.9,
    height: 50.8,
    alignSelf: 'center',
    alignContent: 'center',
  },
  earlyStartImg: {
    borderRadius: 10,
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '115%',
  },
  analytics: {
    width: 325,
    height: 123.5,
    borderRadius: 10,
    marginTop: 20,
  },
  analyticsImage: {
    position: 'absolute',
    top: 10,
    width: 157,
    height: 120,
  },
  analyticsText: {
    width: 325,
    height: 30,
    fontFamily: 'Futura',
    fontSize: 25,
    fontWeight: 'bold',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: '#dce0e6',
    textAlign: 'center',
  },
  textBox: {
    height: 41,
    alignItems: 'flex-end',
    position: 'absolute',
    bottom: 0,
  },
  achievements: {
    paddingTop: '4%',
    width: '100%',
  },
  achievementsText: {
    textAlign: 'left',
    width: 225,
    height: 26,
    fontFamily: 'Futura',
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  achievementsIconContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginBottom: 20,
  },
  achievementsIcon: {
    marginTop: 15,
    width: 66,
    height: 66,
    opacity: 0.71,
    borderRadius: 10,
    backgroundColor: '#626d7b',
  },
});

export default styles;
